### ISSUE TITLE
/login redirects to /profile

### ISSUE THREAD

**Issue by alister** [FriendsOfSymfony/FOSUserBundle#2245] opened 2016-10-03 16:38 UTC
Following pull request #2236 when a currently-logged in user visits a FOSUser generated page (such as /login, /register, /resetting/request or /register) they will be redirected by default to `/profile` (the route named `fos_user_profile_show`).

To change the default route, add a new key in your Symfony configuration: `fos_user.user.default_route`. 

```yml
    fos_user:
        user:
            default_route: app.my.profile_page
```

This change also means that you can no longer just visit `/login` to login as someone else, but must explicitly logout first. This affected a functional test I had written.

**Comment by XWB** [comment] 2016-10-04 09:15
Ping @core23

**Comment by flavienaudin** [comment] 2016-10-04 10:17
Hi,
Is it possible to disable this "new behaviour" (redirect the loggedIn user to default_route when visiting register/login/reset page) by adding another configuration key (fos_user.user.redirect_logged_in_user : true) ? Sometime it is suitable to let user visit these pages even if they are logged in. 
For example, I used the ResettingController:sendEmailAction() (with username set by hand in the request in another action) to initialise password for HWIoauth-registrated user. Like this, user using Facebook registration, can in the futur, still set a password to connect with their email. Maybe it is not the best way to do (?) and it is better to define completely my own action InitPassword() to let user chooser their password (without the current password unknown by the user himself) ?

**Comment by stloyd** [comment] 2016-10-04 10:19
> This change also means that you can no longer just visit /login to login as someone else, but must explicitly logout first. This affected a functional test I had written.

IMO it looks like you were using _bug_ as a workaround for testing, while correct flow is what you described. 

IMO this is not BC-break (or bug) in any case as the flow was broken before. But this is just my opinion.

**Comment by core23** [comment] 2016-10-04 18:13
I share @stloyd opinion. This sounds was a bug, no feature. Can you name any popular site that allows you to login as a new user while you are already logged in?

Maybe we could allow null values for the new key to disable this feature?!

**Comment by flavienaudin** [comment] 2016-10-05 08:55
> Maybe we could allow null values for the new key to disable this feature?!
This could be a good option and easy to implement as it just requires to add a condition on the parameter.

**Comment by picks44** [comment] 2016-10-06 08:32
I have an issue related to this one, please see [#2248](https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2248)

**Comment by francoispluchino** [comment] 2016-10-09 14:10
> This sounds was a bug, no feature. Can you name any popular site that allows you to login as a new user while you are already logged in?

@core23 Your question is legitimate, and I agree with you. However, in the case of using the feature `Remember Me`, a user already authenticated (and so using the `RememberMeToken`) will must access to a protected resource by the role `IS_AUTHENTICATED_FULLY`, can not re-authenticate. He will be redirected to the login page, which in turn, will redirected toward the route defined in the config `fos_user.user.default_route`, because the user instance exist. And in this case, it's more like a bug.

And if it's not a bug, in this case, now, what is the best practice for re-authenticate a user that uses a `RememberMeToken`?

And so, how to redirect to another route that the login page?

**Comment by XWB** [comment] 2016-10-12 12:41
Fixed in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2273

**Closed by XWB** 2016-10-12 12:41 UTC

**Comment by flavienaudin** [comment] 2016-10-16 15:30
Thanks
