### ISSUE TITLE
Invalid users are automatically logged in

### ISSUE THREAD

**Issue by romaricdrigon** [FriendsOfSymfony/FOSUserBundle#1983] opened 2015-10-29 15:03 UTC
Hi,

After some actions - registration completion, reset completion - users are automatically logged in.
`LoginManager::logInUser` checks through `UserChecker::checkPostAuth`. Then there is the glitch: it only checks that the users credentials are not expired, but it does not check if the account is expired or locked.

Solution: `LoginManager::logInUser` should also call `UserChecker::checkPreAuth`.

**Comment by romaricdrigon** [comment] 2015-10-29 15:08
Note that fixing that issue on userland is especially difficult - because `LoginManager:: logInUser()` is declared `final`, so it can only be partially fixed through overriding the `AuthenticationListener`.

**Comment by xabbuh** [comment] 2015-10-30 12:12
Looks like this is related to #1834.

**Comment by romaricdrigon** [comment] 2015-10-30 17:11
Yes it is. I hope it get merged soon!

**Comment by rtuin** [comment] 2016-09-19 13:18
That was merged! Can you confirmed it solves this issue?

**Closed** 2016-10-12 09:29 UTC
