### ISSUE TITLE
[ServiceNotFound] You have requested a non-existent service "fos_user.doctrine_registry"

### ISSUE THREAD

**Issue by yceruto** [FriendsOfSymfony/FOSUserBundle#2058] opened 2016-02-01 15:51 UTC
Today I updated my deps and get the following error:
![fos-user-bug](https://cloud.githubusercontent.com/assets/2028198/12721983/8dc3acd6-c8d0-11e5-8fe1-274177595dfe.png)

The problem is [here](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/DependencyInjection/FOSUserExtension.php#L52):
```php
// ../DependencyInjection/FOSUserExtension.php
//...
$container->setAlias('fos_user.doctrine_registry', new Alias(self::$doctrineDrivers[$config['db_driver']]['registry'], false));
//...
```
when I change `false` by `true` all works fine.

**Comment by stof** [comment] 2016-02-01 15:57
Duplicate of https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2048. The bug has already been fixed in the dev versions of Symfony (all maintained branches) and will be available in the next Symfony releases.

**Closed by stof** 2016-02-01 15:57 UTC

**Comment by yceruto** [comment] 2016-02-01 16:15
:+1:
