### ISSUE TITLE
The route "/group/{groupName}/delete" doesn't works

### ISSUE THREAD

**Issue by LeSTroo53** [FriendsOfSymfony/FOSUserBundle#2698] opened 2018-01-05 16:11 UTC
**Symfony versions**:
3.4.2

**Symfony FOSUserBundle versions**:
2.0.2

**Description of the problem including expected versus actual behavior**:
Hi, i've test all the route from the FOSUserBundle and when tried to delete a group i've an error :
```
An exception occurred while executing 'DELETE FROM fos_group WHERE id = ?' with params [3]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`crmimmoprodsymfony`.`fos_user_user_group`, CONSTRAINT `FK_B3C77447FE54D947` FOREIGN KEY (`group_id`) REFERENCES `fos_group` (`id`))
```

It seemed there are a problem with foreign key in the table "fos_user_user_group".

**Steps to reproduce**:
 1. create a group (ADMIN)
 2. add some user
 3. delete this group with /group/ADMIN/delete

Thx if you can check this.

**Comment by Tomsgu** [comment] 2018-01-08 09:18
I think this is an expected behavior. If the group has some users inside, than it's not possible to delete it. But if you want to have this feature you can override `GroupManager`. [Here](https://symfony.com/doc/master/bundles/FOSUserBundle/user_manager.html#overriding-the-user-manager) you can find how to do. This is for the `UserManager`, but the same you can do for `GroupManager`.

**Comment by LeSTroo53** [comment] 2018-01-09 14:55
Thx for your answer, you are right. After checking that, i need to override `GroupManager` for what i need to do. But i ask myself why don't use "removeGroup" in the class `User`. This is use in relationship's tables between `user` and `fos_group` ?

**Comment by Tomsgu** [comment] 2018-01-09 16:44
Well if you use controllers from this bundle the easiest way is to implement your own GroupManager. RemoveGroup method will not help to you because in delete action there is nothing about user. You should see GroupController : deleteAction for more information.

**Comment by stof** [comment] 2018-01-09 17:45
my suggestion is to avoid using the Group feature of FOSUserBundle. This feature was added in the bundle very early, at a time Symfony had no role hierarchy, and it is mostly unmaintained since then.

**Comment by LeSTroo53** [comment] 2018-01-10 17:27
Ok, but I'm using also FOSUserBundle for the group of user. That's the way i can add roles without using the command line. I did an admin for it and it works perfectly at this time unless the route "/group/ADMIN/delete". 

@Tomsgu have a great idea by overriding `GroupManager` and i'm working on it. 

Actually i succeed to overriding the deleteGroup method but it missed the `user` object. I see that tomorrow if i had time.

Thx for your answers !

**Comment by LeSTroo53** [comment] 2018-01-11 17:03
Ok i find a way !
**First of all** : I forgot to say that i create a many-to-many relationship between `user` and `fos_group`. But this relationship was Unidirectional. So i've change it to a Bidirectional and it works perfectly.

Thx for your answers !

**Comment by stof** [comment] 2022-08-27 12:16
Closing this as the feature has been removed in 3.0

**Closed by stof** 2022-08-27 12:16 UTC
