### ISSUE TITLE
Apache restart after submit login form

### ISSUE THREAD

**Issue by aondarra** [FriendsOfSymfony/FOSUserBundle#1804] opened 2015-04-16 11:08 UTC
I have a project with SQL server DB. I use FOSUserBundle. after submit login form my apache server resets.
SQL server 2012. Apache/2.4.9
PHP 5.5.11

**Comment by xabbuh** [comment] 2015-04-16 12:19
Looks like a duplicate of #1689.

**Comment by stof** [comment] 2015-04-16 23:15
I'm closing this one as duplicate.

And given I don't have SQL server, I fear you will have to debug it. I won't be able to help much.

**Closed by stof** 2015-04-16 23:15 UTC
