### ISSUE TITLE
XmlDriver Exception migrating to PHP 8.2

### ISSUE THREAD

**Issue by yard-mschwartz** [FriendsOfSymfony/FOSUserBundle#3065] opened 2023-12-11 12:03 UTC
**Symfony FOSUserBundle versions**: `dev-master` (v3.2.1 at the time of writing)

**Description of the problem including expected versus actual behavior**:

Application runs just fine on PHP 7.4, but of course we need to migrate to PHP 8.x rather sooner than later. After setting the PHP-version to `^8.2` and running `composer update`, Symfony automatically runs `symfony console cache:clear` for us. Then the following error appears:

```
$ symfony console cache:clear

 [WARNING] Some commands could not be registered:                                                                       

In XmlDriver.php line 1006:

  Warning: DOMDocument::schemaValidate(): Invalid Schema
```

When I go to that line, it shows:

```
try {
    $document = new DOMDocument();
    $document->load($file);

    if (! $document->schemaValidate(__DIR__ . '/../../../../../doctrine-mapping.xsd')) {
        throw MappingException::fromLibXmlErrors(libxml_get_errors());
    }

    ...
}
```

When I dump the value of `$file`, it shows `[...]/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml`, as if that file is not a valid mapping file. Symfony didn't complain about this while I was still on version PHP 7.4.

Obviously the recommended approach is to move away from this library, but maybe someone knows a quick fix for this. Quite possible that this error is more related to Doctrine than to this bundle, but decided to ask here first.

**Comment by yard-mschwartz** [comment] 2023-12-13 14:01
As of now, it appears to be a problem with libxml 2.12 that comes with modern PHP-versions: https://github.com/doctrine/orm/issues/11117

**Comment by stof** [comment] 2024-01-16 16:24
Closing this in favor of the doctrine/orm issue as this is not a bug in FOSUserBundle but an issue in the Doctrine ORM XSD schema itself.

**Closed by stof** 2024-01-16 16:24 UTC
