### ISSUE TITLE
PostgreSQL-9.4.14-1-Windows and FOSUserBundle ~2.0

### ISSUE THREAD

**Issue by methodeprog** [FriendsOfSymfony/FOSUserBundle#2610] opened 2017-09-27 18:54 UTC

**Comment by stof** [comment] 2017-09-28 07:40
Closing as there is no explanation of what the issue is, so there is nothing we can do.

**Closed by stof** 2017-09-28 07:40 UTC

**Comment by methodeprog** [comment] 2017-09-28 14:06
Hi Christophe
Its Ok thanks



2017-09-28 9:40 GMT+02:00 Christophe Coevoet <notifications@github.com>:
