### ISSUE TITLE
after do any action (login, register, logout) throw an exception

### ISSUE THREAD

**Issue by DorZ11** [FriendsOfSymfony/FOSUserBundle#1758] opened 2015-02-23 20:55 UTC
I dont think I did any change since it really new project (Im learning symfony and im newbie) but I get the error while I try to register login or logout. I succeed to login/logout/register (those actions I know. maybe there are more that I didnt try out.) anyway after I return to the page I see that I success to logout/login/register but it just throw me the error. think its routing error but I dont know how to fix it. 

any way there is the error:
Logs  -
1 error

    ERROR - Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost/mySecondApplication/web/app_dev.php/login")" at E:\wamp\www\mySecondApplication\app\cache\dev\classes.php line 2017
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".

**Comment by xabbuh** [comment] 2015-02-24 09:16
@DorZ11 This is not really related to this bundle. You are possibly trying to access a resource under `/` in your app. Since this path is protected (given your actual firewall configuration), you have to log in first. After this is done, you are redirected back to the resource you initially requested and now that you are authenticated, the Symfony router tries to find a matching route for this path. Obviously, you didn't set up a route for `/` yet. If you did this [as described in the book](http://symfony.com/doc/current/book/routing.html), everything should be fine.

**Comment by stof** [comment] 2015-02-24 10:37
Closing because the issue is not related to FOSUserBundle

**Closed by stof** 2015-02-24 10:37 UTC
