### ISSUE TITLE
Hi! Can you help me .... I got an error: Cannot redeclare class Symfony\Component\DependencyInjection\ContainerAwareInterface

### ISSUE THREAD

**Issue by dmitryChernukh** [FriendsOfSymfony/FOSUserBundle#2063] opened 2016-02-03 16:26 UTC
http://stackoverflow.com/questions/35176150/error-in-symfont-2-8-cannot-redeclare-class-symfony-component-dependencyinject

I raised this topic in **stackoverflow**. 

Please, help me if you can.

**Comment by xabbuh** [comment] 2016-02-03 18:08
I fail to see how this is related to FOSUserBundle (also a duplicate of javiereguiluz/EasyAdminBundle#853).

**Closed** 2016-02-29 15:38 UTC
