### ISSUE TITLE
allow NULL for email

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSUserBundle#982] opened 2013-01-30 14:56 UTC
we are combining FOSUserBundle with LiipOneallBundle and sometimes we do not have an email for the user. in this case we would like to leave the email at NULL and therefore also the canonical email should be NULL. unique constraints allow multiple NULL values so it shouldnt cause issues with the unique constraint.

**Comment by 12th** [comment] 2015-06-17 00:20
Override attributes is done via annotations, but when you try to update the following command gets the essence of the exception:
```
php app/console doctrine:generate:entities AppUserBundle:User --no-backup

[Doctrine\ORM\Mapping\MappingException]                                          
Invalid field override named 'username' for class 'App\UserBundle\Entity\User'.  
```
And when you try to update the table no problem:
```
php app/console doctrine:schema:update --force

Updating database schema...
Database schema updated successfully! "4" query was executed
```
=====================================================
```
namespace App\UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * User
 *
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="App\UserBundle\Entity\UserRepository")
 * @ORM\AttributeOverrides({
 *     @ORM\AttributeOverride(name="username",
 *          column=@ORM\Column(
 *              nullable = true
 *          )
 *      ),
 *     @ORM\AttributeOverride(name="usernameCanonical",
 *          column=@ORM\Column(
 *              name = "username_canonical",
 *              nullable = true
 *          )
 *      ),
 *     @ORM\AttributeOverride(name="email",
 *          column=@ORM\Column(
 *              nullable = true
 *          )
 *      ),
 *     @ORM\AttributeOverride(name="emailCanonical",
 *          column=@ORM\Column(
 *              name = "email_canonical",
 *              nullable = true
 *          )
 *      )
 * })
 */
class User extends BaseUser
{
 ...
}
```
=====================================================
composer.json
```
 "require": {
        "doctrine/orm": "~2",
        "doctrine/doctrine-bundle": "~1",
         ...
}
```

Why is the table updated but failed to generate the entity?

**Comment by MHaendel** [comment] 2015-09-08 01:30
Same problem, still no solution?

**Comment by gabiudrescu** [comment] 2015-09-13 18:32
Up. I'm having the same problem - I rely on a social register service to provide access to an application and I need to create unique users based on their tokens, not on their email. Email is optional and most of the time is null.

I have tried everything so far - the closest I came to my business requirement is the situation described above by @12th 

Entity Yaml config file:
```
GabiU\UsersBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    attributeOverride:
          email:
              unique: true
              nullable: true
              ignoreNull: true
          emailCanonical:
              unique: true
              nullable: true
              ignoreNull: true
          password:
              nullable: true
```

```
php app/console doctrine:schema:update --dump-sql
ALTER TABLE fos_user CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE email_canonical email_canonical VARCHAR(255) DEFAULT NULL;
CREATE UNIQUE INDEX UNIQ_957A6479E7927C74 ON fos_user (email);
```

```
php app/console doctrine:generate:entities GabiU --no-backup
Generating entities for namespace "GabiU"


                                                                                           
  [Doctrine\ORM\Mapping\MappingException]                                                  
  Invalid field override named 'email' for class 'GabiU\UsersBundle\Entity\User'.  
```

basically, if I get it right, the only way to make sure this works without warnings is to stop inheriting BaseUser from FOS and create it myself (by copy paste)?

any help is much appreciated :)

**Comment by gabiudrescu** [comment] 2015-09-13 18:35
Also, I have found this in Doctrine's documentation: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#attribute-override

If I get it right, this means I should change the type of the baseUser from entity to type: mappedSuperclass in order to make these overwrites work. I don't know how good is this idea, given FOSUB is a vendor bundle and the modification could be overwritten by a simple composer update.

**Comment by andyexeter** [comment] 2015-10-10 23:31
Bumping. Same issue here when trying to run `doctrine:generate:entities` having overridden the `emailCanonical` column:

 [Doctrine\ORM\Mapping\MappingException]                                           
  Invalid field override named 'emailCanonical' for class 'AppBundle\Entity\User'.`

**Comment by Craimasjien** [comment] 2015-10-19 14:26
A fix for this issue is rather simple. If you use version 1.3.6 of the FOSUserBundle, make sure you *use* 
```
FOS\UserBundle\Entity\User
```
as the superclass for your subclass, instead of *using*
```
FOS\UserBundle\Model\User
```

**Comment by andyexeter** [comment] 2015-10-21 13:08
@Craimasjien I already use `FOS\UserBundle\Entity\User` as the superclass for my subclass. I tried using `Model\User` just in case you got them the wrong way round but the error is presented either way.

**Comment by AienTech** [comment] 2015-11-27 08:32
Still having this issue! Using ```FOSUserBundle 2.0@dev ``` and ```Symfony 2.7```.
extending FOSUSer User Model getting this error:
``` [Doctrine\ORM\Mapping\MappingException] Invalid field override named 'username' for class 'Admin\CustomerBundle\Entity\Customer'.```

**Comment by zaartix** [comment] 2016-01-09 21:50
Symfony 3.0.1 still having this issue

**Comment by AienTech** [comment] 2016-01-10 10:03
extending `FOS\UserBundle\Entity\User` will do the work for now, but need to think about a mere working solution.

**Comment by mlpo** [comment] 2016-01-24 16:20
I just try, I have the same issue.

**Comment by EWaterman** [comment] 2016-03-28 23:11
My issue was with validation. This is what worked for me (I'm using doctrine):

In your user entity:
```

use FOS\UserBundle\Model\User as BaseUser;

/**
 * Account
 *
 * @ORM\Table(name="fos_user")
 * @ORM\AttributeOverrides({
 *     @ORM\AttributeOverride(name="email",
 *          column=@ORM\Column(name="email", type="string", length=50, unique=false, nullable=true)
 *      ),
 *     @ORM\AttributeOverride(name="emailCanonical",
 *         column=@ORM\Column(name="emailCanonical", type="string", length=50, unique=false, nullable=true)
 *     )
 * })
 */
class User extends BaseUser
```

Then in vendor/friendsofsymfony/user-bundle/Resources/doctrine-mapping/validation.xml

Remove the following constraint to email:

```
            <constraint name="NotBlank">
                <option name="message">fos_user.email.blank</option>
                <option name="groups">
                    <value>Registration</value>
                    <value>Profile</value>
                </option>
            </constraint>
```

**Comment by xDaizu** [comment] 2016-04-13 11:00
@AienTech 
> extending FOS\UserBundle\Entity\User will do the work for now, but need to think about a mere working solution.

FOS\UserBundle\Entity\User does not exist (anymore?). We're stuck with `FOS\UserBundle\Model\User`. How do we solve the "generate:entities" bug? (Schema update works fine)

**Comment by stof** [comment] 2016-04-13 12:16
> How do we solve the "generate:entities" bug? (Schema update works fine)

@xDaizu this has nothing to do with this ticket

**Comment by xDaizu** [comment] 2016-04-13 13:40
@stof you're certainly right, it doesn't, but it has to do with the workaround... and since no one is talking about the fix, the workaround will have to do for the time being... won't it? :sweat_smile:

**Comment by murnieza** [comment] 2016-05-10 09:31
So did anyone come up with proper solution or workaround?

**Comment by chalasr** [comment] 2016-05-10 11:20
@murnieza For now, there is no proper solution.

But, as @stof pointed it, this issue is directly related to doctrine and the `AttributeOverrides` behavior, as it should be reproducible for any model that is not part of a 3rd party bundle (is there someone that already given a try between two "local" model?). 

My workaround is to call `setEmail()` systematically from the `setUsername()` method (or constructor), with the username as value (it's sufficient to my need). 
Also, as you are trying to make the email field nullable, you can set a default value that you can use as "null", i.e. `('empty' == $user->getEmail()) ? 'Has no email' : 'Has email';` instead of `(null === $user->getEmail())`.

It's quick and dirty, but should do the trick.

**Comment by codepushr** [comment] 2016-05-29 19:47
+1

**Comment by cocciagialla** [comment] 2016-06-29 07:41
@stof @murnieza
I am currently using two entity managers in my doctrine conf named 'default' and 'global'.

I have the same error `[Doctrine\ORM\Mapping\MappingException] Invalid field override named 'email' `
when doctrine try to search for mapping of the FOSUserBundle as it is not present in the chain.

My solution is to change the mapping for only the second entity manager named 'global' from:
`FOSUserBundle: ~`
to
```
FOSUserBundle:
  type: xml
  dir: '%kernel.root_dir%/../vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping'
  prefix:  FOS\UserBundle\Model
  is_bundle:  false
```

**Comment by armandobasha** [comment] 2016-09-04 19:11
I solved the problem with generate:entities by commenting out the attributeOverride just to generate the entity and then uncomment it.

**Comment by davidll** [comment] 2017-04-20 15:09
I have the same issue with symfony 3.1 and doctrine 2.5, any updates?

**Comment by tecjam** [comment] 2017-07-26 07:51
I am having the same major problem at the moment. 

Is there still no fix or workaround?

**Comment by fredericlam** [comment] 2017-10-11 15:54
Same with Symfony 3.3, Doctrine ORM 2.5 and FOSUserBundle 2.0

**Comment by fredericlam** [comment] 2017-10-11 16:01
Same here with Symfony 3.3, Doctrine 2.5 and FOSUserBundle 2.0.

**Comment by ThomasLabstep** [comment] 2017-10-12 09:18
Same problem here but it's definitely between AttributeOverride and the generate entities command that something goes wrong.

Our quickfix for now is to disable AttributeOverride annotation before generating entities getters and setters.

The annotations AttributeOverride are the right fix to extend User or Group attribute defined in doctrine-mapping XML files.

**Comment by fredericlam** [comment] 2017-10-12 09:24
Thanks @ThomasLabstep . 

So I guess updating the database with doctrine:schema:update --force is ok . 
Then do you know if FOSUserBundle works fully, or at least, as much as before you put AttributeOverride annotations ?

**Comment by ThomasLabstep** [comment] 2017-10-12 10:02
Without override:
```
ALTER TABLE fos_group CHANGE name name VARCHAR(255) NOT NULL;
CREATE UNIQUE INDEX UNIQ_4B019DDB5E237E06 ON fos_group (name);
```

With override:
Nothing to update - your database is already in sync with the current entity metadata.

My annotation looks like this:
```
 * @ORM\AttributeOverrides({
 *      @ORM\AttributeOverride(name="name",
 *          column=@ORM\Column(
 *              nullable = true,
 *              unique   = false,
 *              length   = 255
 *          )
 *      )
 * })
```

**Comment by fredericlam** [comment] 2017-10-12 10:05
Ok, thanks. 

It's more tricky to put email and username nullable + unique = false. 

My main concern was the general feature of FOSUser if we do allow empty email (+canonical) and username(+canonical). Is everything working well with the annotations ?
That's what I'm testing now.

**Comment by ThomasLabstep** [comment] 2017-10-12 10:11
Yes you should all FOSUserBundle controller endpoints and services methods with your change. It might break.

The relevant issue is also described here:
https://github.com/doctrine/doctrine2/issues/4734

**Comment by ThomasLabstep** [comment] 2017-10-12 10:17
OK I found the fix dead buried into Doctrine2 github tickets.
https://github.com/doctrine/doctrine2/issues/3433

You need to modify manually a file in vendor to fix the issue. It actually generated getters and setters that were previously ignored entirely by the generate entity command.

In Doctrine\Common\Persistence\Mapping\StaticReflectionService

Replace:
```
    public function getParentClasses($class)
    {
        return [];
    }
```

By:
```
    public function getParentClasses($class)
    {
        if ( ! class_exists($class)) {
            throw MappingException::nonExistingClass($class);
        }

        return class_parents($class);
    }
```

**Comment by fredericlam** [comment] 2017-10-12 12:58
Ok, awesome.
We have a workaround until a fix for it.

**Comment by meistersoda** [comment] 2018-01-11 14:49
I am facing the same problem. What is the best way to use the workaround? I dont want to implement it after every composer update/install. Whats the best practice or do we have to wait until doctrine fixes it?

**Comment by fredericlam** [comment] 2018-01-11 14:52
@meistersoda concerning me, the only thing I had to do is to remove

` * @AttributeOverrides({
 *     @AttributeOverride(name="emailCanonical",
 *         column=@ORM\Column(
 *             name="emailCanonical",
 *             type="string",
 *             length=255,
 *             unique=false
 *         )
 *     )
 * })`

every time I want to regenerate entities. 
It works then when you want to update your database schema.

**Comment by meistersoda** [comment] 2018-01-11 15:12
@fredericlam That's so simple I didn't even think about it.

Thanks! ;)

**Comment by aanthraxx** [comment] 2018-03-21 03:58
March 2018

Still have this issue. 

my work around is by removing the `@AttributeOverrides` like what @armandobasha did.
Hope they fix this issue.

**Comment by slince** [comment] 2018-07-25 05:10
+up

**Comment by julkwel** [comment] 2019-04-02 18:23
I'm on 4.0 and use the following annotations
`
* @AttributeOverrides({
 *     @ORM\AttributeOverride(name="email",
 *          column=@ORM\Column(
 *              nullable = true,
 *              unique=false
 *          )
 *      )
 * })
`

**Closed** 2021-09-02 15:44 UTC
Labels: Enhancement

**Comment by tomazartack** [comment] 2023-03-01 15:23
Having this issue still with Symfony 4.4.50, Doctrine ORM 2.14.1 and FOS User Bundle 2.2.4. Do I need to update my dependencies to solve this issue?
