### ISSUE TITLE
Mail not sent in fosuserbundle with symfony 2.8

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSUserBundle#2024] opened 2016-01-05 11:43 UTC
Please visit http://stackoverflow.com/questions/34596190/symfony-swiftmailer-mail-not-sent-in-prod-environment

**Comment by xabbuh** [comment] 2016-01-05 11:47
duplicate of symfony/swiftmailer-bundle#128

**Comment by antondachauer** [comment] 2016-01-05 11:49
Right, but that is another bundle and maybe another developer team.

**Comment by ybensacq** [comment] 2016-01-29 23:59
I have a project on symfony 2.8 with fos user bundle, and mail in prod are well sent.

**Comment by XWB** [comment] 2016-10-12 11:57
This is not the right place.

**Closed by XWB** 2016-10-12 11:57 UTC
