### ISSUE TITLE
Symfony 2.6 compatibility issues

### ISSUE THREAD

**Issue by lordpato** [FriendsOfSymfony/FOSUserBundle#1722] opened 2015-01-15 20:23 UTC
Is there any WIP updates regarding Symfony 2.6 compatibility?.
Any ETA for a testing bundle?

Thanks in advance!

**Comment by xabbuh** [comment] 2015-01-15 22:07
@lordpato Is there anything that doesn't work for you with Symfony 2.6?

**Comment by algofond** [comment] 2015-01-16 13:42
Same problem here. For example, the bundle still uses SecurityContextInterface which is deprecated in Symfony 2.6. In the dev-mode this yields a lot of Deprecated-Exceptions. Furthermore, CsrfProviderAdapter classs is deprecated as well etc.

**Comment by xabbuh** [comment] 2015-01-16 13:56
@algofond Are you sure that you use Symfony 2.6? Deprecation notices should only be triggered when using Symfony 2.7.

**Comment by lordpato** [comment] 2015-01-16 14:00
Exactly that's the issue I see. Symfony version 2.6.3 (new installation).

--
Gastón Sebastián Marengo

2015-01-16 10:56 GMT-03:00 Christian Flothmann <notifications@github.com>:

**Comment by xabbuh** [comment] 2015-01-16 14:03
Can you show the stack trace of such a notice and also show what output you get when executing `composer show -i` for your project?

**Comment by stof** [comment] 2015-01-16 14:04
@lordpato I'm using FOSUserBundle with Symfony 2.6, and I'm not getting deprecation warnings. Symfony 2.6 does not have any such warnings

**Comment by algofond** [comment] 2015-01-17 17:56
@xabbuh it seems that you are right: after restoring the previous config composer installed indeed a Symfony 2.7-dev version. After a rollback to vesion 2.6.3 all the warnings disappeared. Therefore the problem is essentially a 2.7-dev issue which is related to a compatibility problem between the bundle und Symfony 2.6. Hence lets reformulate the question: will you treat this problem until a release of a stable 2.7 version?

**Comment by stof** [comment] 2015-01-18 08:59
Yes, we defintely will update it before the 2.7 stable release. But I prefer keeping the support for 2.3 for now and bumping the requirement to 2.6+ only a bit later (but before the 2.7 release)

**Comment by algofond** [comment] 2015-01-18 21:20
@stof Great, that solves our problem

**Comment by dannyalfonzo** [comment] 2015-01-23 12:57
Hi guys, I have not worked with symfony since version 2.1 and now retake on a project that I have, I wanted to know if I can use the version 2.6 with confidence that this bundle will work

Thanks

**Comment by toolpixx** [comment] 2015-01-23 14:03
Hi,

sorry, i have commit my change, this was a mistake.

regards

Am 23.01.2015 um 13:57 schrieb dannyalfonzo:
>
> Hi guys, I have not worked with symfony since version 2.1 and now 
> retake on a project that I have, I wanted to know if I can use the 
> version 2.6 with confidence that this bundle will work
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1722#issuecomment-71189616>.
>

-- 

Mit freundlichen Grüßen
Andreas van Loock

--
TOOLPIXX

Andreas van Loock
Boffertsweg 61
53489 Sinzig
---
Mobil    : +49 (0) 16 3  - 69 810 69
eMail    : a.vanloock@toolpixx.com
Internet : www.toolpixx.com

**Comment by stof** [comment] 2015-01-23 17:03
@dannyalfonzo see my previous comment on this. the bundle is totally compatible with 2.6.

anyway closing thr issue as @algofond reported he was actually using 2.7 when seeing deprecation warnings

**Closed by stof** 2015-01-23 17:03 UTC
