### ISSUE TITLE
Can't install with PHP 7.2

### ISSUE THREAD

**Issue by dgoujard** [FriendsOfSymfony/FOSUserBundle#2835] opened 2018-08-14 11:23 UTC
**Symfony FOSUserBundle versions**: 2.1.X

**Description of the problem including expected versus actual behavior**:
When i try to install FOSUserBundle in my SF4.1.3 project on PHP 7.2.1 i got an error with dependency paragonie/random_compat.
I think it's related to this FAQ in random_compat : https://github.com/paragonie/random_compat#version-99999
The composer.json in FOSUserBundle need to be updated to handle special version 99999

**Provide logs (if relevant)**:
```
php7.2.1/bin/php ../composer.phar require friendsofsymfony/user-bundle "~2.1" paragonie/random_compat
Using version ^9.99 for paragonie/random_compat
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofsymfony/user-bundle v2.1.2 requires paragonie/random_compat ^1 || ^2 -> satisfiable by paragonie/random_compat[1.0.10, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, v1.0.0, v1.0.1, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.3.0, v1.3.1, v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.x-dev, v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9] but these conflict with your requirements or minimum-stability.
    - friendsofsymfony/user-bundle v2.1.1 requires paragonie/random_compat ^1 || ^2 -> satisfiable by paragonie/random_compat[1.0.10, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, v1.0.0, v1.0.1, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.3.0, v1.3.1, v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.x-dev, v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9] but these conflict with your requirements or minimum-stability.
    - friendsofsymfony/user-bundle v2.1.0 requires paragonie/random_compat ^1 || ^2 -> satisfiable by paragonie/random_compat[1.0.10, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, v1.0.0, v1.0.1, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.3.0, v1.3.1, v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.x-dev, v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9] but these conflict with your requirements or minimum-stability.
    - Installation request for friendsofsymfony/user-bundle ~2.1 -> satisfiable by friendsofsymfony/user-bundle[v2.1.0, v2.1.1, v2.1.2].
```

Installation failed, reverting ./composer.json to its original content.

**Comment by dgoujard** [comment] 2018-08-14 11:32
This issue is resolved by this commit https://github.com/FriendsOfSymfony/FOSUserBundle/commit/007fd9bd48a17d23b1c38b01115db202db7d989c but not released yet

**Comment by Tomsgu** [comment] 2018-08-14 16:11
Yes and this issue is duplicate of #2830 in advance.

**Comment by Axiioss** [comment] 2018-09-04 12:15
Any news on when we can expect this issue fixed? I can see that it is fixed in master, so i guess it will be in tag 2.1.3

**Comment by stof** [comment] 2018-09-04 13:08
Well, the reason it fails here is because you are also requiring `paragonie/random_compat` explicitly, but without a version, and so composer guesses a version constraint as `^9.99`. Without that, things might work fine (`paragonie/random_compat` 2.0.9 works perfectly fine on PHP 7.2)

**Comment by dgoujard** [comment] 2018-09-04 13:58
@stof if i didn't provide `paragonie/random_compat` explicitly it's fail too. I need to use dev-master version to work with PHP 7.2.

**Comment by Axiioss** [comment] 2018-09-04 14:09
yes i didn't have `paragonie/random_compat` in my composer.json and according to 2.1.2 it requires `^1 ||^2` but in master it seams to have been fixed. So i am guessing we need to wait for 2.1.3 for it to work. All i ask is when is it ETA?

**Comment by respinoza** [comment] 2018-09-06 00:46
@stof  I don't have `paragonie/random_compat` in my composer.json and I see this behavior.
Fix is already on master, it is just a matter of tagging next release.

**Comment by numediaweb** [comment] 2018-09-27 10:36
I also don't have `paragonie/random_compat` on my composer or project (except that `symfony/polyfill-php70` requires it).. What fixed it for me is:
```
composer require paragonie/random_compat ^2.0
composer require friendsofsymfony/user-bundle "~2.0"
```

**Closed** 2019-03-05 10:33 UTC
